#!/usr/bin/env bash
#
# Persistence testing script
#
SCYLLADB_VERSION="2.0.2"
DOCKER_ID=$(docker run --detach "scylladb/scylla:${SCYLLADB_VERSION}")

#
# Tear down
#
function cleanup() {
    docker rm -f "${DOCKER_ID}" &> "/dev/null"
}
trap cleanup EXIT

#
# Check docker components
#
sleep "5s"
SCYLLA_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' "${DOCKER_ID}")
export SCYLLA_IP

#
# Run testing
#
go test -v -a "./..."
