#!/usr/bin/env bash
#
# Metadata testing script
#
ELASTIC_VERSION="2.4.1"
DOCKER_ID=$(docker run --detach "elasticsearch:${ELASTIC_VERSION}")

#
# Tear down
#
function cleanup() {
    docker rm -f "${DOCKER_ID}" &> "/dev/null"
}
trap cleanup EXIT

#
# Check docker components
#
sleep "2s"
ELASTIC_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' "${DOCKER_ID}")
export ELASTIC_IP

#
# Run testing
#
go test -v -a "./..."
